version: 2
jobs:
  build:
    docker:
      - image: node:10
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-cache-{{ arch }}-{{ .Branch }}-{{ checksum "package-lock.json" }}-{{ checksum "elm.json" }}
      - run:
          name: Install elm
          command: >
            mkdir ~/.npm-global
            && npm config set prefix '~/.npm-global'
            && npm install --unsafe-perm -g elm@0.19.0-bugfix6
      - run:
          name: Install dependencies
          command: make setup
      - run:
          name: Build project
          command: make dist
      - run:
          name: Test project
          command: make test
      - save_cache:
          key:  v2-cache-{{ arch }}-{{ .Branch }}-{{ checksum "package-lock.json" }}-{{ checksum "elm.json" }}
          paths:
            - /root/.elm
            - elm-stuff
            - node_modules
